import type { FunctionRegistryItem } from './types'

/**
 * Central catalog of all Quarkdown stdlib functions exposed in the editor UI.
 * Each entry drives serialization, form rendering, and the command palette.
 */
export const CATALOG: FunctionRegistryItem[] = [
  // -------------------------------------------------------------------------
  // Document metadata
  // -------------------------------------------------------------------------
  {
    id: 'doctype',
    canonicalName: 'doctype',
    displayName: 'Document Type',
    category: 'document',
    intentTags: ['doctype', 'type', 'plain', 'paged', 'slides', 'docs'],
    description: 'Sets the document output type.',
    syntaxKind: 'block',
    placement: 'document-meta',
    params: [
      {
        name: 'type',
        displayName: 'Type',
        type: 'enum',
        required: true,
        enumValues: ['plain', 'paged', 'slides', 'docs'],
        description: 'Output document type.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'document-setup',
    serializerTemplate: '.doctype {{{type}}}',
    examples: [{ source: '.doctype {paged}', description: 'Set to paged (LaTeX-like) output.' }],
    icon: 'FileText',
  },
  {
    id: 'docname',
    canonicalName: 'docname',
    displayName: 'Document Title',
    category: 'document',
    intentTags: ['title', 'name', 'document'],
    description: 'Sets the document title.',
    syntaxKind: 'block',
    placement: 'document-meta',
    params: [
      {
        name: 'value',
        displayName: 'Title',
        type: 'string',
        required: true,
        description: 'The document title.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'document-setup',
    serializerTemplate: '.docname {{{value}}}',
    examples: [{ source: '.docname {My Document}', description: 'Set document title.' }],
    icon: 'TextT',
  },
  {
    id: 'docauthor',
    canonicalName: 'docauthor',
    displayName: 'Author',
    category: 'document',
    intentTags: ['author', 'metadata', 'by'],
    description: 'Sets the document author.',
    syntaxKind: 'block',
    placement: 'document-meta',
    params: [
      {
        name: 'name',
        displayName: 'Name',
        type: 'string',
        required: true,
        description: 'Author full name.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'document-setup',
    serializerTemplate: '.docauthor {{{name}}}',
    examples: [{ source: '.docauthor {Jane Doe}', description: 'Single author.' }],
    icon: 'User',
  },
  {
    id: 'docdescription',
    canonicalName: 'docdescription',
    displayName: 'Description',
    category: 'document',
    intentTags: ['description', 'abstract', 'summary'],
    description: 'Sets the document description or abstract.',
    syntaxKind: 'block',
    placement: 'document-meta',
    params: [
      {
        name: 'value',
        displayName: 'Description',
        type: 'string',
        required: true,
        description: 'Short description of the document.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'document-setup',
    serializerTemplate: '.docdescription {{{value}}}',
    examples: [],
    icon: 'AlignLeft',
  },
  {
    id: 'doclanguage',
    canonicalName: 'doclanguage',
    displayName: 'Language',
    category: 'document',
    intentTags: ['language', 'locale', 'i18n'],
    description: 'Sets the document locale (e.g. en, fr, pt-BR).',
    syntaxKind: 'block',
    placement: 'document-meta',
    params: [
      {
        name: 'tag',
        displayName: 'Language tag',
        type: 'string',
        required: true,
        defaultValue: 'en',
        description: 'BCP-47 language tag.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'document-setup',
    serializerTemplate: '.doclanguage {{{tag}}}',
    examples: [{ source: '.doclanguage {pt-BR}', description: 'Brazilian Portuguese.' }],
    icon: 'Globe',
  },
  {
    id: 'theme',
    canonicalName: 'theme',
    displayName: 'Theme',
    category: 'themes',
    intentTags: ['theme', 'layout', 'color', 'style'],
    description: 'Sets the layout and/or color theme.',
    syntaxKind: 'block',
    placement: 'document-meta',
    params: [
      {
        name: 'layout',
        displayName: 'Layout',
        type: 'string',
        required: false,
        description: 'Layout theme name.',
        likelyNamed: true,
        likelyBody: false,
      },
      {
        name: 'color',
        displayName: 'Color',
        type: 'string',
        required: false,
        description: 'Color theme name.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'document-setup',
    serializerTemplate: '.theme layout:{{{layout}}} color:{{{color}}}',
    examples: [{ source: '.theme layout:{latex} color:{darcula}', description: 'LaTeX layout with Darcula colors.' }],
    icon: 'Palette',
  },
  {
    id: 'tableofcontents',
    canonicalName: 'tableofcontents',
    displayName: 'Table of Contents',
    category: 'document',
    intentTags: ['toc', 'table of contents', 'index'],
    description: 'Inserts an auto-generated table of contents.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'title',
        displayName: 'Title',
        type: 'string',
        required: false,
        description: 'Override the TOC heading text.',
        likelyNamed: true,
        likelyBody: false,
      },
      {
        name: 'maxdepth',
        displayName: 'Max depth',
        type: 'number',
        required: false,
        defaultValue: 3,
        description: 'Maximum heading depth to include.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'toolbar-button',
    serializerTemplate: '.tableofcontents',
    examples: [{ source: '.tableofcontents', description: 'Insert TOC.' }],
    icon: 'List',
  },

  // -------------------------------------------------------------------------
  // Layout
  // -------------------------------------------------------------------------
  {
    id: 'container',
    canonicalName: 'container',
    displayName: 'Container',
    category: 'layout',
    intentTags: ['container', 'box', 'wrapper', 'div', 'width', 'align'],
    description: 'A styled container block with optional dimensions, color, and alignment.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'width',
        displayName: 'Width',
        type: 'size',
        required: false,
        description: 'Container width (e.g. 80%, 400px).',
        likelyNamed: true,
        likelyBody: false,
      },
      {
        name: 'alignment',
        displayName: 'Alignment',
        type: 'enum',
        required: false,
        enumValues: ['left', 'center', 'right'],
        description: 'Horizontal alignment of the container.',
        likelyNamed: true,
        likelyBody: false,
      },
      {
        name: 'background',
        displayName: 'Background color',
        type: 'color',
        required: false,
        description: 'Background color.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'form-panel',
    serializerTemplate: '.container{{#width}} width:{{{width}}}{{/width}}{{#alignment}} alignment:{{{alignment}}}{{/alignment}}\n    {{{body}}}',
    examples: [
      {
        source: '.container width:{80%} alignment:{center}\n    Content goes here.',
        description: 'Centered 80% container.',
      },
    ],
    icon: 'SquareDashed',
  },
  {
    id: 'align',
    canonicalName: 'align',
    displayName: 'Align',
    category: 'layout',
    intentTags: ['align', 'center', 'left', 'right'],
    description: 'Aligns block content horizontally.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'alignment',
        displayName: 'Alignment',
        type: 'enum',
        required: true,
        enumValues: ['left', 'center', 'right'],
        description: 'Horizontal alignment.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'toolbar-button',
    serializerTemplate: '.align {{{alignment}}}\n    {{{body}}}',
    examples: [{ source: '.align {center}\n    Centered text.', description: 'Center-align content.' }],
    icon: 'AlignCenterHorizontal',
  },
  {
    id: 'column',
    canonicalName: 'column',
    displayName: 'Multi-Column Layout',
    category: 'layout',
    intentTags: ['column', 'columns', 'multi-column', 'two-column'],
    description: 'Arranges content in multiple columns side by side.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'count',
        displayName: 'Column count',
        type: 'number',
        required: false,
        defaultValue: 2,
        description: 'Number of columns.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'wizard-modal',
    serializerTemplate: '.column\n    {{{body}}}',
    examples: [{ source: '.column\n    Left\n\n    Right', description: 'Two-column layout.' }],
    icon: 'Columns',
  },
  {
    id: 'box',
    canonicalName: 'box',
    displayName: 'Box / Callout',
    category: 'layout',
    intentTags: ['box', 'callout', 'note', 'warning', 'tip', 'info'],
    description: 'A styled callout box with an optional title and type.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'type',
        displayName: 'Type',
        type: 'enum',
        required: false,
        enumValues: ['info', 'warning', 'error', 'tip', 'success'],
        description: 'Visual type of the box.',
        likelyNamed: true,
        likelyBody: false,
      },
      {
        name: 'title',
        displayName: 'Title',
        type: 'string',
        required: false,
        description: 'Optional heading for the box.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'form-panel',
    serializerTemplate: '.box{{#type}} type:{{{type}}}{{/type}}{{#title}} title:{{{title}}}{{/title}}\n    {{{body}}}',
    examples: [{ source: '.box type:{warning} title:{Heads up}\n    Be careful here.', description: 'Warning callout.' }],
    icon: 'Info',
  },
  {
    id: 'pagebreak',
    canonicalName: 'pagebreak',
    displayName: 'Page Break',
    category: 'layout',
    intentTags: ['page break', 'new page', 'break'],
    description: 'Forces a page break (for paged documents).',
    syntaxKind: 'block',
    placement: 'block',
    params: [],
    bodyMode: 'none',
    uiControl: 'toolbar-button',
    serializerTemplate: '.pagebreak',
    examples: [{ source: '.pagebreak', description: 'Force page break.' }],
    icon: 'ArrowLineDown',
  },

  // -------------------------------------------------------------------------
  // Media
  // -------------------------------------------------------------------------
  {
    id: 'figure',
    canonicalName: 'figure',
    displayName: 'Figure',
    category: 'media',
    intentTags: ['figure', 'image', 'caption', 'photo'],
    description: 'An image with an optional caption, wrapped as a document figure.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'src',
        displayName: 'Source',
        type: 'string',
        required: true,
        description: 'Image file path or URL.',
        likelyNamed: false,
        likelyBody: false,
      },
      {
        name: 'caption',
        displayName: 'Caption',
        type: 'string',
        required: false,
        description: 'Figure caption text.',
        likelyNamed: true,
        likelyBody: false,
      },
      {
        name: 'width',
        displayName: 'Width',
        type: 'size',
        required: false,
        description: 'Image display width.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'wizard-modal',
    serializerTemplate: '.figure {{{src}}}{{#caption}} caption:{{{caption}}}{{/caption}}{{#width}} width:{{{width}}}{{/width}}',
    examples: [{ source: '.figure {diagram.png} caption:{System diagram}', description: 'Captioned figure.' }],
    icon: 'Image',
  },

  // -------------------------------------------------------------------------
  // Tables
  // -------------------------------------------------------------------------
  {
    id: 'table',
    canonicalName: 'table',
    displayName: 'Table',
    category: 'tables',
    intentTags: ['table', 'grid', 'data', 'rows', 'columns'],
    description: 'Generates a table from CSV-like data or Markdown pipe syntax.',
    syntaxKind: 'block',
    placement: 'block',
    params: [],
    bodyMode: 'raw',
    uiControl: 'wizard-modal',
    serializerTemplate: '{{{body}}}',
    examples: [
      {
        source: '| Name | Age |\n|------|-----|\n| Alice | 30 |',
        description: 'Standard Markdown table.',
      },
    ],
    icon: 'Table',
  },

  // -------------------------------------------------------------------------
  // Diagrams
  // -------------------------------------------------------------------------
  {
    id: 'mermaid',
    canonicalName: 'mermaid',
    displayName: 'Mermaid Diagram',
    category: 'diagrams',
    intentTags: ['mermaid', 'diagram', 'flowchart', 'sequence', 'graph'],
    description: 'Renders a Mermaid diagram from a code block.',
    syntaxKind: 'block',
    placement: 'block',
    params: [],
    bodyMode: 'raw',
    uiControl: 'wizard-modal',
    serializerTemplate: '```mermaid\n{{{body}}}\n```',
    examples: [
      {
        source: '```mermaid\ngraph TD\n    A --> B\n```',
        description: 'Simple flowchart.',
      },
    ],
    icon: 'GitBranch',
  },

  // -------------------------------------------------------------------------
  // Math
  // -------------------------------------------------------------------------
  {
    id: 'math',
    canonicalName: 'math',
    displayName: 'Math Block',
    category: 'math',
    intentTags: ['math', 'latex', 'katex', 'equation', 'formula'],
    description: 'Renders a KaTeX math block.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'expression',
        displayName: 'Expression',
        type: 'string',
        required: true,
        description: 'LaTeX math expression.',
        likelyNamed: false,
        likelyBody: true,
      },
    ],
    bodyMode: 'raw',
    uiControl: 'wizard-modal',
    serializerTemplate: '$$\n{{{expression}}}\n$$',
    examples: [{ source: '$$\nE = mc^2\n$$', description: 'Einstein mass-energy equation.' }],
    icon: 'MathOperations',
  },

  // -------------------------------------------------------------------------
  // References
  // -------------------------------------------------------------------------
  {
    id: 'footnote',
    canonicalName: 'footnote',
    displayName: 'Footnote',
    category: 'references',
    intentTags: ['footnote', 'note', 'reference'],
    description: 'Inserts a footnote reference (GFM syntax).',
    syntaxKind: 'inline',
    placement: 'inline',
    params: [
      {
        name: 'content',
        displayName: 'Content',
        type: 'string',
        required: true,
        description: 'Footnote content.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'inline-action',
    serializerTemplate: '[^{{id}}]\n\n[^{{id}}]: {{{content}}}',
    examples: [
      { source: 'Hello[^1]\n\n[^1]: World', description: 'GFM footnote.' },
    ],
    icon: 'Asterisk',
  },

  // -------------------------------------------------------------------------
  // Variables
  // -------------------------------------------------------------------------
  {
    id: 'let',
    canonicalName: 'let',
    displayName: 'Variable (let)',
    category: 'variables',
    intentTags: ['variable', 'let', 'assign', 'value', 'store'],
    description: 'Declares a local variable with a value.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'name',
        displayName: 'Name',
        type: 'string',
        required: true,
        description: 'Variable name (no dot prefix).',
        likelyNamed: false,
        likelyBody: false,
      },
      {
        name: 'value',
        displayName: 'Value',
        type: 'string',
        required: true,
        description: 'Value assigned to the variable.',
        likelyNamed: false,
        likelyBody: true,
      },
    ],
    bodyMode: 'raw',
    uiControl: 'form-panel',
    serializerTemplate: '.let {{{name}}}\n    {{{value}}}',
    examples: [{ source: '.let {myvar}\n    Hello', description: 'Declare variable myvar = "Hello".' }],
    icon: 'Variable',
  },
  {
    id: 'var',
    canonicalName: 'var',
    displayName: 'Variable (var)',
    category: 'variables',
    intentTags: ['variable', 'var', 'mutable', 'reassign'],
    description: 'Declares a mutable variable that can be reassigned.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'name',
        displayName: 'Name',
        type: 'string',
        required: true,
        description: 'Variable name.',
        likelyNamed: false,
        likelyBody: false,
      },
      {
        name: 'value',
        displayName: 'Initial value',
        type: 'string',
        required: true,
        description: 'Initial value of the variable.',
        likelyNamed: false,
        likelyBody: true,
      },
    ],
    bodyMode: 'raw',
    uiControl: 'form-panel',
    serializerTemplate: '.var {{{name}}}\n    {{{value}}}',
    examples: [{ source: '.var {count}\n    0', description: 'Mutable counter variable.' }],
    icon: 'Variable',
  },

  // -------------------------------------------------------------------------
  // Logic
  // -------------------------------------------------------------------------
  {
    id: 'if',
    canonicalName: 'if',
    displayName: 'Conditional (if)',
    category: 'logic',
    intentTags: ['if', 'conditional', 'when', 'condition'],
    description: 'Conditionally renders content based on a boolean expression.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'condition',
        displayName: 'Condition',
        type: 'string',
        required: true,
        description: 'Boolean expression (e.g. .isgreater {.count} {0}).',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'form-panel',
    serializerTemplate: '.if {{{condition}}}\n    {{{body}}}',
    examples: [{ source: '.if {.isgreater {.count} {0}}\n    Count is positive.', description: 'Conditional output.' }],
    icon: 'ArrowFatLinesRight',
  },
  {
    id: 'foreach',
    canonicalName: 'foreach',
    displayName: 'For Each Loop',
    category: 'logic',
    intentTags: ['foreach', 'loop', 'iterate', 'repeat'],
    description: 'Iterates over a collection, rendering a lambda for each item.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'collection',
        displayName: 'Collection',
        type: 'string',
        required: true,
        description: 'The collection to iterate over.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'lambda',
    uiControl: 'form-panel',
    serializerTemplate: '.foreach {{{collection}}}\n    {{{body}}}',
    examples: [
      {
        source: '.foreach {.range {1} {5}} item:\n    Item .item',
        description: 'Print items 1 through 5.',
      },
    ],
    icon: 'Repeat',
  },
  {
    id: 'repeat',
    canonicalName: 'repeat',
    displayName: 'Repeat',
    category: 'logic',
    intentTags: ['repeat', 'times', 'loop', 'n times'],
    description: 'Repeats a block of content a given number of times.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'times',
        displayName: 'Times',
        type: 'number',
        required: true,
        description: 'Number of repetitions.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'form-panel',
    serializerTemplate: '.repeat {{{times}}}\n    {{{body}}}',
    examples: [{ source: '.repeat {3}\n    Row\n', description: 'Repeat "Row" 3 times.' }],
    icon: 'ArrowsClockwise',
  },

  // -------------------------------------------------------------------------
  // Slides
  // -------------------------------------------------------------------------
  {
    id: 'slides-fragment',
    canonicalName: 'fragment',
    displayName: 'Slide Fragment',
    category: 'slides',
    intentTags: ['fragment', 'reveal', 'animation', 'step'],
    description: 'Marks content as a reveal.js fragment that appears on click.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'style',
        displayName: 'Animation style',
        type: 'enum',
        required: false,
        enumValues: ['fade-in', 'fade-out', 'grow', 'shrink', 'highlight-red', 'highlight-blue'],
        description: 'Fragment reveal animation.',
        likelyNamed: true,
        likelyBody: false,
      },
    ],
    bodyMode: 'markdown',
    uiControl: 'form-panel',
    serializerTemplate: '.fragment{{#style}} style:{{{style}}}{{/style}}\n    {{{body}}}',
    examples: [{ source: '.fragment style:{fade-in}\n    Revealed on click.', description: 'Fade-in fragment.' }],
    icon: 'PlayCircle',
  },
  {
    id: 'slides-speakernotes',
    canonicalName: 'speakernotes',
    displayName: 'Speaker Notes',
    category: 'slides',
    intentTags: ['speaker notes', 'notes', 'presenter', 'aside'],
    description: 'Adds speaker notes visible only in presenter mode.',
    syntaxKind: 'block',
    placement: 'block',
    params: [],
    bodyMode: 'markdown',
    uiControl: 'form-panel',
    serializerTemplate: '.speakernotes\n    {{{body}}}',
    examples: [{ source: '.speakernotes\n    Remember to smile!', description: 'Speaker note.' }],
    icon: 'Microphone',
  },

  // -------------------------------------------------------------------------
  // Advanced
  // -------------------------------------------------------------------------
  {
    id: 'function',
    canonicalName: 'function',
    displayName: 'Custom Function',
    category: 'advanced',
    intentTags: ['function', 'define', 'custom', 'macro', 'reusable'],
    description: 'Defines a reusable custom function with named parameters.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'name',
        displayName: 'Function name',
        type: 'string',
        required: true,
        description: 'Name of the function (without leading dot).',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'raw',
    uiControl: 'wizard-modal',
    serializerTemplate: '.function {{{name}}}\n    {{{body}}}',
    examples: [
      {
        source: '.function {greet} name:\n    Hello, .name!',
        description: 'Define a function that greets by name.',
      },
    ],
    icon: 'Function',
  },
  {
    id: 'include',
    canonicalName: 'include',
    displayName: 'Include File',
    category: 'advanced',
    intentTags: ['include', 'import', 'file', 'subdocument'],
    description: 'Includes another .qd file into this document.',
    syntaxKind: 'block',
    placement: 'block',
    params: [
      {
        name: 'path',
        displayName: 'File path',
        type: 'string',
        required: true,
        description: 'Relative path to the .qd file.',
        likelyNamed: false,
        likelyBody: false,
      },
    ],
    bodyMode: 'none',
    uiControl: 'form-panel',
    serializerTemplate: '.include {{{path}}}',
    examples: [{ source: '.include {intro.qd}', description: 'Include intro.qd.' }],
    icon: 'FolderOpen',
  },
]

export default CATALOG
